Add scan build example
GoogleCloudPlatform/cloud-build-samples pull request #6
Opened 2021-04-06 14:08 UTC by geriom

Build example to scan a container for vulnerabilities.

2021-04-13 18:49 UTC, dinagraves requested changes
I created a PR against your branch with all my suggestions!  Please feel free to push back on anything.

2021-04-13 18:49 UTC, dinagraves commented on scan-build-example/cloudbuild.yaml
> +       docker build -t us-central1-docker.pkg.dev/$_PROJECT_ID/ods-build-repo/ods-test:latest -f ./Dockerfile . &&
Why not use the [default PROJECT_ID](https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#:~:text=Cloud%20Build%20provides%20the%20following,%24PROJECT_NUMBER%20%3A%20your%20project%20number)?

2021-04-13 18:49 UTC, dinagraves commented on scan-build-example/cloudbuild.yaml
> +       --format='value(vulnerability.effectiveSeverity)' | if grep -Fxq $_SEVERITY; \
Would it be worth providing a default severity in the cloudbuild.yaml?  Or do you want this to always be passed in via substitutions? This [sample](https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#yaml_2) shows default values.

2021-04-13 18:49 UTC, dinagraves commented on scan-build-example/cloudbuild.yaml
> +       gcloud artifacts docker images scan us-central1-docker.pkg.dev/$_PROJECT_ID/ods-build-repo/ods-test:latest \
Style nit: can you make the lines shorter?  Maybe store this big long image name as a shorter variable?

2021-04-13 18:49 UTC, dinagraves commented on scan-build-example/cloudbuild.yaml
> +   - id: push
This explicit step is unnecessary if you use the "images" config below.  That pushes it to the registry.  You only need one or the other.  If you have both, you may be pushing twice.

2021-04-23 18:21 UTC, geriom commented on scan-build-example/cloudbuild.yaml
> +       docker build -t us-central1-docker.pkg.dev/$_PROJECT_ID/ods-build-repo/ods-test:latest -f ./Dockerfile . &&
I think your observation makes sense, in most scenarios the project will match the active project.

2021-04-23 18:21 UTC, geriom commented on scan-build-example/cloudbuild.yaml
> +       --format='value(vulnerability.effectiveSeverity)' | if grep -Fxq $_SEVERITY; \
I would prefer to pass it via substitutions, otherwise the default value may be perceived as the "recommended" acceptable vulnerability level.

2021-04-23 20:53 UTC, dinagraves approved these changes

2021-04-23 20:53 UTC, merged